### ISSUE TITLE
Consoleまわりを完全に理解できていない

### ISSUE THREAD

**Issue by tmokmss** [tmokmss/FPSSample#2]
https://github.com/tmokmss/FPSSample/tree/master/Assets/Scripts/Console

* ビューとロジックの分離
* マルチプラットフォーム化(linux/win)

あたりがおもしろポイントか

**Comment by tmokmss** [comment]
コンソール：主にデバッグ用途で用いられると思われる、コマンドラインインターフェース
インゲームではF1キーで呼び出せる
SkyrimとかL4Dとか色々なゲームで似たような機能は存在する

`ConsoleUI`: コンソールのViewに必要なメソッドを宣言したインターフェース
これを実装したクラスが3つある：
* `ConsoleGUI`: uGUIを用いた実装
* `ConsoleTextWin`: WinAPI使ってアタッチしたコマンドプロンプトプロセスを用いる実装
* `ConsoleTextLinux`: `System.Console` を用いるコンソール実装

後ろ2つはheadlessモード（dedicated server的なやつ）で起動したときに用いられる
（UnityのGUIはなしにサーバーだけ起動するのでそれはそう）

ConsoleTextLinuxをWindowsで使えない理由は何なんだろう
Linuxの方のコードはあまりOSに依存している感がない

初期化時は Game.cs L294 あたりで #ifマクロなどでプラットフォームごとに振り分けられている。
https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Game/Main/Game.cs#L294-L305

**Comment by tmokmss** [comment]
`Console` クラス

コンソールのモデル
各コンソールコマンドの実装であったり、Tab補完や履歴機能などコンソールに必要なロジックが実装されている
GUIは `ConsoleUI` インターフェースを通して操作するので、Viewとロジックが疎結合に保たれている

コマンドはAddCommandメソッドで追加する
https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Console/Console.cs#L98-L107
コマンド文字列と、実行するメソッドをデリゲートで渡す
デリゲートの参照先は全て staticメソッドであり、状態を持たないようになっている（特定のインスタンスの参照を必要としない）
じゃあどうやってデバッグ機能でよくあるパラメータ変更するねんと思うが、パラメータの変更は `vars` コマンドに集約されている

そもそも操作可能なゲームパラメータは `ConfigVar` というクラス内で管理されている
これは ConfigVarAttribute をつけたフィールドをリフレクションで全て取得し、一括に辞書登録するhttps://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Game/Core/ConfigVars.cs#L124
https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Game/Systems/GameMode/GameModeSystemServer.cs#L39-L42
なお現状は、登録した変数の値を書き換えることはできない模様
ただ一括でリスト出力する機能があるのみだ

また、ConfigVar は staticフィールド以外許可しないようなので、特定のインスタンスの変数はいじれないようである（プレイヤー3のHPのみ2倍にするとか）
そりゃグローバル変数みたいなもんなので当たり前ではあるが、これでも事足りるんだろうか

Source Engine系のゲームだとこういうのはよく出てきたのを思い出した
https://developer.valvesoftware.com/wiki/List_of_HL2_Cvars

**Comment by sugiish** [comment]
# デバッグ機能
コンフル見てて思ったのはデバッグ機能のための機能を用意しだすと大体つらいということ。
Console クラスはビューとモデルを分離しているので、どう表示するかはほとんど気にしなくていい設計になっている。

## 気になったところ
### パイプのサポート
ConsoleTextLinux はパイプ入出力をサポートしてそう。外部からの操作が前提って感じか。
それ以外は ConsoleTextWin とロジック的な違いはないように思える。

https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Console/ConsoleTextLinux.cs#L29-L44

### シーン遷移など
ゲームループで必要なデバッグ機能はこの辺で突っ込んでいる。シーン遷移系。

https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Game/Main/Game.cs#L428-L449

遷移するときは一旦キューに突っ込んで、それが処理されるのを待つみたい。この辺面白い。
https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Game/Main/Game.cs#L249-L257

### そのほか
どうでもいいけど ConsoleNullUI って必要なんだろうか。
https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Console/Console.cs#L18

`command` と `cmd` が併用されているのが気になったが、後者は methodDelegate にしか使っていないので混同はしなかった。個人的にはこういう略し方は好きじゃないけど、分かりやすい。

**Comment by sugiish** [comment]
> また、ConfigVar は staticフィールド以外許可しないようなので、特定のインスタンスの変数はいじれないようである（プレイヤー3のHPのみ2倍にするとか）
そりゃグローバル変数みたいなもんなので当たり前ではあるが、これでも事足りるんだろうか

必要な機能は Entity 経由から値を操作することで実現しているように思える。 `RespawnPlayer` とか参考になりそう。
https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Game/Main/ServerGameLoop.cs#L86-L96

呼び出し元はここ。
https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Game/Main/ServerGameLoop.cs#L699-L727

**Comment by tmokmss** [comment]
おお `Console.AddCommand` てConsoleクラス内じゃなくて色んな所から呼ばれてるんだな
`static` メソッド以外を追加したら寿命問題（Consoleクラスに登録されているものの呼び出し先インスタンスは破棄されている、あるいはGCされずメモリーリーク）が発生すると思ったが、下記の方法でちゃんとケアされている
1. AddCommand時にインスタンスの `GetHashCode` をTagとして渡す
2. インスタンス破棄時に、そのインタンスのHashCodeで登録されたコマンドを破棄する
https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Console/Console.cs#L114-L124
https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Game/Main/ServerGameLoop.cs#L376-L379

**Comment by SuguruYamashita** [comment]
実行もできなかったので、Console.csを一通り読んで自分なりの思ったことと何をしているのかを想像でコメントしてみました〜
https://gist.github.dena.jp/suguru-yamashita/144b36726b2341f942b7a953e880b786#file-console-cs-L21

**Comment by tmokmss** [comment]
完全理解 on 2019/4/16
