### ISSUE TITLE
Network周りの構成を完全に理解できてない

### ISSUE THREAD

**Issue by tmokmss** [tmokmss/FPSSample#4]
この辺り読んでまず構成から探ろう
https://github.com/tmokmss/FPSSample/tree/master/Assets/Scripts/Networking

**Comment by tmokmss** [comment]
* クライアント - サーバー方式
    * NetworkServer
        * クライアントの接続や切断、データ送受信
        * ゲームに必要な演算はこちらでやっているらしい
    * NetworkClient

## NetworkServer
メインループ
https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Networking/NetworkServer.cs#L361-L381
* m_Transport からイベントを受け取り、 https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Networking/Socket/SocketTransport.cs#L38
* OnConnect/Disconnect/Data の3種のイベントに振り分けてそれぞれ処理

https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Networking/NetworkServer.cs#L688-L695
* OnData（→ ReadPackage）で、Packageというものからコマンドやイベントを読み取っている
    * ここではキューするだけ
    * ServerGameLoop でHandleClientCommandsなどが呼び出され、まとめて処理する https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Game/Main/ServerGameLoop.cs#L174-L175

## NetworkClient
* 実装はかなりServerに似ている https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Networking/NetworkClient.cs#L205
* CommandHandleのようなメソッドは（当然）こちらにはない


## INetworkTransport
* 接続・切断・データの送受信などを抽象化した層
https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Networking/NetworkCommon.cs#L18-L31
* 実装は `SocketTransport` （UDPのソケット通信）と `TestTransport`（メモリ内で完結するテスト用）


## Package
* いわゆるパケット
* ヘッダーの情報を利用してデータの順番を決めたり損失を検出したりできるようだ
    * ヘッダーをパースするメソッドはちょっと読む気にならない https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Networking/NetworkConnection.cs#L163

**Comment by MasafumiYamamoto** [comment]
# 参考資料
[slackにも貼られていたブログ記事](http://hadashia.hatenablog.com/entry/2018/12/02/212621)

そもそもとして、サーバーもクライアントもC#とUnityで完結している(C#大統一理論を感じる)
Yellowでは通信周りはIRIS使ってましたね。
Server、Clientともに本体と{Server,Client}MainLoopを読めばとりあえずよさそう。
サーバーではServer.HandleClientEvent()などで実際のクライアントの行動やらのゲーム内アップデートは起きている？
Client側はReadSnapShot()でサーバーから受け取ったデータを利用して同期をとっていそうな雰囲気。
どちらも詳細をよく読むのはこれから。

全体的な流れとして、サーバー側で総合的なロジックを進めつつ、クライアントではサーバーと共有が取れていない間は独自にロジックを進め、サーバーからのデータ共有の段階で独自にすすめていた情報を破棄し、サーバーとの同期を取る、みたいな流れを採用しているとのこと。

通信方式としてはUDPらしい
TCPと比べると通信の安定性や確実性が損なわれるものの、速度面からUDPを採用しているようだ
YellowでもTCP的なことはやっていなかった気がする
順番ずれだったりパケット消失だったり重複だったりにももちろん対応している


# 気になった点
- ITransport.Update()の中身も読み進める必要がありそうだ
- INetworkTransportに一括して送受信データをまとめているんですね
    - Yellowの時は攻撃判定や死亡判定などは個別に投げてた気がする
    - きっとEventの中身を見ていくとそのように別れているのだろう
- Client.Update()の中でやっている、ReadSnapShot()が重くて今回は読むのを断念
- 共有回数少ないけどこれで体験として問題ないのか
    - キャラの動きとか攻撃とかの密に共有してほしそうな情報も毎フレーム同期しているわけではないようだ
