### ISSUE TITLE
Network周り上層を完全に理解できてない

### ISSUE THREAD

**Issue by tmokmss** [tmokmss/FPSSample#5]
Snapshotとか

**Comment by tmokmss** [comment]
* Snapshot
    * ある瞬間におけるEntityの状態を全て保存したデータ
    * 生成時刻と長さと先頭ポインタを持つクラス https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Networking/NetworkServer.cs#L526-L531
    * `unsafe` は基本
        * mallocまである https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Networking/NetworkServer.cs#L103
        * 当然freeも https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Networking/NetworkServer.cs#L116
* Snapshotの生成 https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Networking/NetworkServer.cs#L234
  * すべてのEntityを走査して、EntityごとにSnapshotを生成し、NetworkWriterでbyte配列にappendしていく
  * 一つのEntityのSnapshot生成はここでやってる https://github.com/tmokmss/FPSSample/blob/cd1e82dafccc540e2ce4cb28ad05bc4be6bc2211/Assets/Scripts/Game/Modules/ReplicatedEntity/ReplicatedEntityCollection.cs#L248
    * Snapshot生成時はEntityをSerializeするのだが、それは個々に実装してるっぽい https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Game/Modules/Player/Components/PlayerState.cs#L53-L61
        * リフレクションとかは使わないのだな
    * ここでは圧縮とか考えずにすべてのデータを格納している模様
* 圧縮はどこ？
    * `m_Snapshot` 配列（リングバッファ）を用いて圧縮かけてるのは明らか
    * これ使ってるのが他に `WriteSnapshot` メソッドだけなので、ここでやってそう https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Networking/NetworkServer.cs#L823
* 圧縮処理は `TOutputSream` で決まるが、これは上から `HuffmanOutputStream` が渡ってきている https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Networking/Compression/HuffmanOutputStream.cs#L5
    * これがデルタ圧縮の本体？ https://github.com/tmokmss/FPSSample/blob/147f4719b61c2857d342bc0722c88d165bab3378/Assets/Scripts/Networking/Compression/HuffmanOutputStream.cs#L69-L74
        * ベースライン（基準となるSnapshot）と差をとってインターリーブ（0, -1, 1, -2, 2 → 0, 1, 2, 3, 4と変換)する
        * この結果バイト列の要素がだいたい同じような値になるので、ハフマン符号的には圧縮率上がるということなのか？
* predictionとかsnapshotの解凍のあたり気になったがまだ読めてない

**Comment by MasafumiYamamoto** [comment]
それぞれのEntityに対してSnapShotを作成しているが、各Entityではspawn,despawn,updateの情報だけをSnapShotとして保持しているようだ
worldの話はそもそも気が付かなかった・・・
Client側ではProcessShapShot()でSnapShotの適用をしているが、実際にSnapShotの内容を適用するかどうかを計算しているのはProcessSnapShot()に入る前に決まっているようだ(SnapShotが適切な内容かどうかの判断など)
実際にSnapShotの差分を適用しているのはReadPackedUInt()だろうが、未読。

そもそもの疑問として、ハフマン木の構築はどの段階で行っているのか？
インターリーブの話を見る限り、０～Nまででそのまま予め構築している？
差分ならだいたい0になるというのはそれはそうといった感じもする。
