### ISSUE TITLE
ダメージ処理を完全に理解できていない

### ISSUE THREAD

**Issue by MasafumiYamamoto** [tmokmss/FPSSample#6]

**Comment by MasafumiYamamoto** [comment]
各Entity(実際はキャラクターだろう)がDynamicBuffer<DamageEvent>のdamageBufferを持っており、ここが更新されることでダメージが蓄積されるシステムであるように見える。

DamageEvent.AddEvent()が呼び出されている場所を追っていく方針でダメージ処理を追っていく。
DamageEvent.AddEvent()が呼び出されているのは以下の箇所

- Melee_HandleCollision.Update()
- AutoRifle_HandleCollisionQuery.Update()
- CharacterDebugWindow.OnGUI()
- DamageAreaSystemServer.OnUpdate()
- HandleProjectiveMovementCollisionQuery.OnUpdate()
- HandleSplashDamageRequests.Damage()

順次見ていきましょう。

## Melee_HandleCollision.Update()
Meleeとは乱闘らしい
処理内容としてはAutoRifleとほぼ同じようなので割愛。

## AutoRifle_HandleCollisionQuery.Update()
このあたりを理解するにはそもそもEntityComponentManager.GetComponentDataを理解する必要がありそうだ。
internalState.rayQueryIdが弾の攻撃範囲が有効かどうかのフラグになっていそうだが、ここを更新しているのはどこなのか。
rayQuertIdだと弾の生成時に設定されていそうだが、Ability_AutoRifle.Update()で毎回-1に設定されているようだ。
        var queryReciever = World.GetExistingManager<RaySphereQueryReciever>();
        RaySphereQueryReciever.Query query;
        RaySphereQueryReciever.QueryResult queryResult;
        queryReciever.GetResult(internalState.rayQueryId, out query, out queryResult);
        internalState.rayQueryId = -1;
rayQueryIdの更新はともかく、このあと弾がヒットしていればダメージを適用してAddEventしている


## CharacterDebugWindow.OnGUI()
DebugWindow関連っぽいのでひとまず割愛

## DamageAreaSystemServer.OnUpdate()
そもそもDamageAreaとは、攻撃による攻撃範囲として捉えて問題なさそうだ。
DamageAreaSystemServerにはComponentGroup Groupがあり、ここに攻撃範囲のComponentがリストのような形で格納されているのだろう。
DamageAreaは致死攻撃かどうか、範囲内に存在するキャラクターのリスト、ダメージ値などを保持しており、OnTrigger{Enter,Exit}で範囲内に存在するキャラクターのリストを更新している。

    void OnTriggerEnter(Collider c)
    {
        var hitCollision = c.gameObject.GetComponent<HitCollision>();
        if (hitCollision == null)
            return;


        charactersInside.Add(new CharacterInfo {hitCollisionOwner = hitCollision.owner, nextDamageTick = 0});
    }    

    void OnTriggerExit(Collider c)
    {
        var hitCollision = c.gameObject.GetComponent<HitCollision>();
        if (hitCollision == null)
            return;


        for (var i = 0; i < charactersInside.Count; i++)
        {
            if (charactersInside[i].hitCollisionOwner == hitCollision.owner)
            {
                charactersInside.EraseSwap(i);
                break;
            }
        }
    }

そしてここで更新したリストに基づき、DamageAreaSystemServerのOnUpdate()中にダメージの有効判定並びにDamageEvent.AddEvent()している

## HandleProjectiveMovementCollisionQuery.OnUpdate()
Projectileは発射体らしい。
処理内容としてはAutoRifleとほぼ同じようなので割愛。


## HandleSplashDamageRequests.Damage()
ここではダメージを計算してただ詰めているだけのようだ。
実際のダメージに使う要素の取得はDamage()で呼び出しているようだ。
人物由来のダメージ発生源とスリップダメージの2種類が存在。


溜めたDamageEventの適用はHealthState.ApplyDamage()ようだが、こちらは次回に持越したい。
誰か読んだ人に解説してほしい。
damageの矛盾解決とかはむしろこの当たりを読むべきな気がする

**Comment by MasafumiYamamoto** [comment]
ApplyDamage読み進め中
CharacterModuleServer.OnUpdate()で呼ばれている。
単純にキャラクターのエンティティに溜まったdamageBufferを順次読み出しているだけのようだ。

そのため、矛盾の解消はむしろここではなく、damageEventの詰め方にあるように見える。
とはいえ、damageBufferの更新がサーバーで行われるように制限することで、矛盾が起きないように調停がすでにできているのでは？

**Comment by tmokmss** [comment]
* ダメージ適用の流れはymmtがまとめてくれたのを信じる
* 弾の発射はどうやって行われるんだろうか？
  * 以前読んだ `UserCommand` に `PrimaryFire` だと `Melee` だのがあった https://github.com/tmokmss/FPSSample/blob/cd1e82dafccc540e2ce4cb28ad05bc4be6bc2211/Assets/Scripts/Game/Modules/Player/UserCommand.cs#L6-L17
    * サーバーにクライアントのキー入力だけが送られて、以後の計算（弾が発射されてから当たってダメージ適用されるまで）はサーバーで行われるんでは
      * それならばクライアント間で相反するリクエストは存在し得ないので、フェアではある気がする
      * 実際に確かめてみよう
* クライアント側でコマンドに状態をセットしている部分 https://github.com/tmokmss/FPSSample/blob/cd1e82dafccc540e2ce4cb28ad05bc4be6bc2211/Assets/Scripts/Game/Modules/Player/PlayerModuleClient.cs#L96-L98
  * primariFireは自動小銃なので長押しで連射できる
    * このため、 `duration < fireDuration` なら発火なんて実装になっているのだろう
    * ここ入力のドメインで銃の連射挙動が決まるのはドメインが漏れてきてる感があるな
  * SecondaryFire入力の実装は謎
    * PrimaryFire が発火するときに必ず発火するようになっている
      * 未実装なのかな？
* Setされたコマンドは `commandBuffer` に格納され、その後NetWorkClient の送信キューにpushされる https://github.com/tmokmss/FPSSample/blob/cd1e82dafccc540e2ce4cb28ad05bc4be6bc2211/Assets/Scripts/Game/Modules/Player/PlayerModuleClient.cs#L201-L218
  * queueされたら前回の仕組みに則ってサーバーに送信され、 ProcessCommand でそれぞれ処理される 
  * `Deserialize` でコマンドをパース https://github.com/tmokmss/FPSSample/blob/cd1e82dafccc540e2ce4cb28ad05bc4be6bc2211/Assets/Scripts/Game/Main/ServerGameLoop.cs#L137-L138
    * サーバー側で持っている、対応するクライアントの latestCommand に受け取ったコマンドをコピーしている
    * さらに `UserCommandComponentData` がクライアントのEntityに登録されて、その後はymmtの解説した仕組みによりダメージが処理される https://github.com/tmokmss/FPSSample/blob/cd1e82dafccc540e2ce4cb28ad05bc4be6bc2211/Assets/Scripts/Game/Main/ServerGameLoop.cs#L143-L149
* 結論、クライアントのキー入力を送信してるだけだから、矛盾するリクエストは存在せず、調停も必要ないってことだろう
